# Generated by Django 4.0.4 on 2022-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.DecimalField(decimal_places=0, max_digits=9)),
                ('número', models.IntegerField()),
            ],
        ),
    ]
