# Generated by Django 2.2.12 on 2022-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_contacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
