# Generated by Django 2.2.12 on 2022-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20220429_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RN', 'Freshman'), ('PB', 'Sophomore'), ('PE', 'Junior')], default='RN', max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
