# Generated by Django 2.2.12 on 2022-04-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_adresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresses',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.Contacts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresses',
            name='state',
            field=models.CharField(choices=[('RN', 'Rio Grade do Norte'), ('PB', 'Paraiba'), ('PE', 'Pernambuco')], default='RN', max_length=2),
        ),
    ]
